from db import db  # Import db from the new module

class File(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    DistrictCode  = db.Column(db.String(100), nullable=False)
    SchoolCode  = db.Column(db.String(100), nullable=False)
    CountyName   = db.Column(db.String(100), nullable=False)
    DistrictName  = db.Column(db.String(100), nullable=False)
    SchoolName   = db.Column(db.String(100), nullable=False)
    ClassID    = db.Column(db.String(100), nullable=False)
    CourseCode   = db.Column(db.String(100), nullable=False)
    ClassCourseID   = db.Column(db.String(100), nullable=False)
    GradeLevelCode    = db.Column(db.String(100), nullable=False)
    GenderCode   = db.Column(db.String(100), nullable=False)
    EnrollNoEthRptd   = db.Column(db.String(100), nullable=False)
    EnrollAmInd    = db.Column(db.String(100), nullable=False)
    EnrollAsian   = db.Column(db.String(100), nullable=False)
    EnrollPacIsl    = db.Column(db.String(100), nullable=False)
    EnrollFilipino     = db.Column(db.String(100), nullable=False)
    EnrollHispanic    = db.Column(db.String(100), nullable=False)
    EnrollAfrAm    = db.Column(db.String(100), nullable=False)
    EnrollWhite     = db.Column(db.String(100), nullable=False)
    EnrollTwoOrMore    = db.Column(db.String(100), nullable=False)
    EnrollTotal     = db.Column(db.String(100), nullable=False)
    EnrollEl    = db.Column(db.String(100), nullable=False)
    GenderCode   = db.Column(db.String(100), nullable=False)
    Content = db.Column(db.Text, nullable=False)
